<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>develop-manual: doctotext::Exception类 参考</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">develop-manual
   &#160;<span id="projectnumber">2021.02</span>
   </div>
   <div id="projectbrief">develop manual about develop-manual</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- 制作者 Doxygen 1.8.13 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'搜索');
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','搜索');
  $(document).ready(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('classdoctotext_1_1_exception.html','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="summary">
<a href="#nested-classes">类</a> &#124;
<a href="#pub-methods">Public 成员函数</a> &#124;
<a href="classdoctotext_1_1_exception-members.html">所有成员列表</a>  </div>
  <div class="headertitle">
<div class="title">doctotext::Exception类 参考</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="3rd_party_2doctotext_2exception_8h_source.html">exception.h</a>&gt;</code></p>
<div class="dynheader">
类 doctotext::Exception 继承关系图:</div>
<div class="dyncontent">
<div class="center"><img src="classdoctotext_1_1_exception__inherit__graph.png" border="0" usemap="#doctotext_1_1_exception_inherit__map" alt="Inheritance graph"/></div>
<map name="doctotext_1_1_exception_inherit__map" id="doctotext_1_1_exception_inherit__map">
</map>
<center><span class="legend">[<a target="top" href="graph_legend.html">图例</a>]</span></center></div>
<div class="dynheader">
doctotext::Exception 的协作图:</div>
<div class="dyncontent">
<div class="center"><img src="classdoctotext_1_1_exception__coll__graph.png" border="0" usemap="#doctotext_1_1_exception_coll__map" alt="Collaboration graph"/></div>
<map name="doctotext_1_1_exception_coll__map" id="doctotext_1_1_exception_coll__map">
</map>
<center><span class="legend">[<a target="top" href="graph_legend.html">图例</a>]</span></center></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
类</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="struct_exception_1_1_implementation.html">Implementation</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public 成员函数</h2></td></tr>
<tr class="memitem:a3af03224ca08ebeb00e47b5182f83887"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a3af03224ca08ebeb00e47b5182f83887">Exception</a> (const std::string &amp;first_error_message)  throw ()</td></tr>
<tr class="separator:a3af03224ca08ebeb00e47b5182f83887"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a832dd48cb8b2f2da191f948aded1a871"><td class="memItemLeft" align="right" valign="top"><a id="a832dd48cb8b2f2da191f948aded1a871"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>Exception</b> (const <a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;ex)  throw ()</td></tr>
<tr class="separator:a832dd48cb8b2f2da191f948aded1a871"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1aefee9ace772a7bcb592e96987f72fa"><td class="memItemLeft" align="right" valign="top"><a id="a1aefee9ace772a7bcb592e96987f72fa"></a>
<a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;ex)  throw ()</td></tr>
<tr class="separator:a1aefee9ace772a7bcb592e96987f72fa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a32cb3156f2adfd140c0bb5b6cd7ad78f"><td class="memItemLeft" align="right" valign="top"><a id="a32cb3156f2adfd140c0bb5b6cd7ad78f"></a>
const char *&#160;</td><td class="memItemRight" valign="bottom"><b>what</b> ()</td></tr>
<tr class="separator:a32cb3156f2adfd140c0bb5b6cd7ad78f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1490b6df103141fa84635a18b5628cec"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a1490b6df103141fa84635a18b5628cec">getBacktrace</a> ()</td></tr>
<tr class="separator:a1490b6df103141fa84635a18b5628cec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49922ad8840470895a5958c9716b518c"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a49922ad8840470895a5958c9716b518c">appendError</a> (const std::string &amp;error_message)</td></tr>
<tr class="separator:a49922ad8840470895a5958c9716b518c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7bae2072b466585125edc5f467ddf2b2"><td class="memItemLeft" align="right" valign="top">std::list&lt; std::string &gt;::iterator&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a7bae2072b466585125edc5f467ddf2b2">getErrorIterator</a> () const</td></tr>
<tr class="separator:a7bae2072b466585125edc5f467ddf2b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac0b8aca0e868e6d04c1f63615bda0c88"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#ac0b8aca0e868e6d04c1f63615bda0c88">getErrorCount</a> () const</td></tr>
<tr class="separator:ac0b8aca0e868e6d04c1f63615bda0c88"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5db39ff707c5408549a705136c760a4b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a5db39ff707c5408549a705136c760a4b">Exception</a> (const std::string &amp;first_error_message)  throw ()</td></tr>
<tr class="separator:a5db39ff707c5408549a705136c760a4b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae10dd7e1e1567a4b3fe2a0e105dd8c5b"><td class="memItemLeft" align="right" valign="top"><a id="ae10dd7e1e1567a4b3fe2a0e105dd8c5b"></a>
&#160;</td><td class="memItemRight" valign="bottom"><b>Exception</b> (const <a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;ex)  throw ()</td></tr>
<tr class="separator:ae10dd7e1e1567a4b3fe2a0e105dd8c5b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8409e8467bfa6309dc6e6f2dc3219e12"><td class="memItemLeft" align="right" valign="top"><a id="a8409e8467bfa6309dc6e6f2dc3219e12"></a>
<a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><b>operator=</b> (const <a class="el" href="classdoctotext_1_1_exception.html">Exception</a> &amp;ex)  throw ()</td></tr>
<tr class="separator:a8409e8467bfa6309dc6e6f2dc3219e12"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a32cb3156f2adfd140c0bb5b6cd7ad78f"><td class="memItemLeft" align="right" valign="top"><a id="a32cb3156f2adfd140c0bb5b6cd7ad78f"></a>
const char *&#160;</td><td class="memItemRight" valign="bottom"><b>what</b> ()</td></tr>
<tr class="separator:a32cb3156f2adfd140c0bb5b6cd7ad78f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab88499ca7184b914041eed0a38c82b9f"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#ab88499ca7184b914041eed0a38c82b9f">getBacktrace</a> ()</td></tr>
<tr class="separator:ab88499ca7184b914041eed0a38c82b9f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac612f8be8b7c1d0f86f9bc33548f37c2"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#ac612f8be8b7c1d0f86f9bc33548f37c2">appendError</a> (const std::string &amp;error_message)</td></tr>
<tr class="separator:ac612f8be8b7c1d0f86f9bc33548f37c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a36a08a0282ccc7e2e50f112a5dadc75f"><td class="memItemLeft" align="right" valign="top">std::list&lt; std::string &gt;::iterator&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a36a08a0282ccc7e2e50f112a5dadc75f">getErrorIterator</a> () const</td></tr>
<tr class="separator:a36a08a0282ccc7e2e50f112a5dadc75f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a73188af3beb4a2f06ad2be5d735878f8"><td class="memItemLeft" align="right" valign="top">size_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classdoctotext_1_1_exception.html#a73188af3beb4a2f06ad2be5d735878f8">getErrorCount</a> () const</td></tr>
<tr class="separator:a73188af3beb4a2f06ad2be5d735878f8"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">详细描述</h2>
<div class="textblock"><p>This class is implementation of std::exception, which is used by DocToText. In this implementation, errors can be formed in "stack".</p>
<p>In order to create exception just call: </p><div class="fragment"><div class="line"><span class="keywordflow">throw</span> Exception(<span class="stringliteral">&quot;First error&quot;</span>);</div></div><!-- fragment --><p>You can catch exception and add one more error: </p><div class="fragment"><div class="line"><span class="keywordflow">catch</span> (Exception&amp; ex)</div><div class="line">{</div><div class="line">    ex.appendError(<span class="stringliteral">&quot;Next error message&quot;</span>);</div><div class="line">    <span class="keywordflow">throw</span>;</div><div class="line">}</div></div><!-- fragment --><p>or you can catch exception and get "backtrace": </p><div class="fragment"><div class="line"><span class="keywordflow">catch</span> (Exception&amp; ex)</div><div class="line">{</div><div class="line">    std::cerr &lt;&lt; ex.getBacktrace();</div><div class="line">}</div></div><!-- fragment --> 
<p class="definition">在文件 <a class="el" href="3rd_party_2doctotext_2exception_8h_source.html">exception.h</a> 第 <a class="el" href="3rd_party_2doctotext_2exception_8h_source.html#l00036">36</a> 行定义.</p>
</div><h2 class="groupheader">构造及析构函数说明</h2>
<a id="a3af03224ca08ebeb00e47b5182f83887"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3af03224ca08ebeb00e47b5182f83887">&#9670;&nbsp;</a></span>Exception() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">Exception::Exception </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>first_error_message</em></td><td>)</td>
          <td></td>
        </tr>
        <tr>
          <td align="right">throw </td><td>(</td><td colspan="2"></td>
        </tr>
        <tr>
          <td align="right"></td><td>)</td><td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The constructor. </p><dl class="params"><dt>参数</dt><dd>
  <table class="params">
    <tr><td class="paramname">first_error_message</td><td>first error message (gives information about cause of an error). </td></tr>
  </table>
  </dd>
</dl>

<p class="definition">在文件 <a class="el" href="exception_8cpp_source.html">exception.cpp</a> 第 <a class="el" href="exception_8cpp_source.html#l00063">63</a> 行定义.</p>

</div>
</div>
<a id="a5db39ff707c5408549a705136c760a4b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5db39ff707c5408549a705136c760a4b">&#9670;&nbsp;</a></span>Exception() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">doctotext::Exception::Exception </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>first_error_message</em></td><td>)</td>
          <td></td>
        </tr>
        <tr>
          <td align="right">throw </td><td>(</td><td colspan="2"></td>
        </tr>
        <tr>
          <td align="right"></td><td>)</td><td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>The constructor. </p><dl class="params"><dt>参数</dt><dd>
  <table class="params">
    <tr><td class="paramname">first_error_message</td><td>first error message (gives information about cause of an error). </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">成员函数说明</h2>
<a id="a49922ad8840470895a5958c9716b518c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a49922ad8840470895a5958c9716b518c">&#9670;&nbsp;</a></span>appendError() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void Exception::appendError </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>error_message</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Adds one more error message. </p>

<p class="definition">在文件 <a class="el" href="exception_8cpp_source.html">exception.cpp</a> 第 <a class="el" href="exception_8cpp_source.html#l00124">124</a> 行定义.</p>

</div>
</div>
<a id="ac612f8be8b7c1d0f86f9bc33548f37c2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac612f8be8b7c1d0f86f9bc33548f37c2">&#9670;&nbsp;</a></span>appendError() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void doctotext::Exception::appendError </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>error_message</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Adds one more error message. </p>

</div>
</div>
<a id="ab88499ca7184b914041eed0a38c82b9f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab88499ca7184b914041eed0a38c82b9f">&#9670;&nbsp;</a></span>getBacktrace() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string doctotext::Exception::getBacktrace </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>returns a string with all error messages. Each error message is separated by "\n". Suppose we have thrown an exception: </p><div class="fragment"><div class="line"><span class="keywordflow">throw</span> Exception(<span class="stringliteral">&quot;First error message&quot;</span>);</div></div><!-- fragment --><p> Next, we have added one more error: </p><div class="fragment"><div class="line">ex.appendError(<span class="stringliteral">&quot;Second error message&quot;</span>);</div></div><!-- fragment --><p> In the result getBacktrace will return a string: "First error message\nSecond error message\n" </p>

</div>
</div>
<a id="a1490b6df103141fa84635a18b5628cec"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1490b6df103141fa84635a18b5628cec">&#9670;&nbsp;</a></span>getBacktrace() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string Exception::getBacktrace </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>returns a string with all error messages. Each error message is separated by "\n". Suppose we have thrown an exception: </p><div class="fragment"><div class="line"><span class="keywordflow">throw</span> Exception(<span class="stringliteral">&quot;First error message&quot;</span>);</div></div><!-- fragment --><p> Next, we have added one more error: </p><div class="fragment"><div class="line">ex.appendError(<span class="stringliteral">&quot;Second error message&quot;</span>);</div></div><!-- fragment --><p> In the result getBacktrace will return a string: "First error message\nSecond error message\n" </p>

<p class="definition">在文件 <a class="el" href="exception_8cpp_source.html">exception.cpp</a> 第 <a class="el" href="exception_8cpp_source.html#l00114">114</a> 行定义.</p>

</div>
</div>
<a id="ac0b8aca0e868e6d04c1f63615bda0c88"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac0b8aca0e868e6d04c1f63615bda0c88">&#9670;&nbsp;</a></span>getErrorCount() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t Exception::getErrorCount </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Returns a number of error messages </p>

<p class="definition">在文件 <a class="el" href="exception_8cpp_source.html">exception.cpp</a> 第 <a class="el" href="exception_8cpp_source.html#l00134">134</a> 行定义.</p>

</div>
</div>
<a id="a73188af3beb4a2f06ad2be5d735878f8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a73188af3beb4a2f06ad2be5d735878f8">&#9670;&nbsp;</a></span>getErrorCount() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">size_t doctotext::Exception::getErrorCount </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Returns a number of error messages </p>

</div>
</div>
<a id="a7bae2072b466585125edc5f467ddf2b2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7bae2072b466585125edc5f467ddf2b2">&#9670;&nbsp;</a></span>getErrorIterator() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::list&lt; std::string &gt;::iterator Exception::getErrorIterator </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>returns a iterator to the first error message </p>

<p class="definition">在文件 <a class="el" href="exception_8cpp_source.html">exception.cpp</a> 第 <a class="el" href="exception_8cpp_source.html#l00129">129</a> 行定义.</p>

</div>
</div>
<a id="a36a08a0282ccc7e2e50f112a5dadc75f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a36a08a0282ccc7e2e50f112a5dadc75f">&#9670;&nbsp;</a></span>getErrorIterator() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::list&lt;std::string&gt;::iterator doctotext::Exception::getErrorIterator </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>returns a iterator to the first error message </p>

</div>
</div>
<hr/>该类的文档由以下文件生成:<ul>
<li>dde-file-manager/dde-file-manager-lib/3rdParty/doctotext/<a class="el" href="3rd_party_2doctotext_2exception_8h_source.html">exception.h</a></li>
<li>dde-file-manager/dde-file-manager-lib/3rdParty/doctotext/<a class="el" href="exception_8cpp_source.html">exception.cpp</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><b>doctotext</b></li><li class="navelem"><a class="el" href="classdoctotext_1_1_exception.html">Exception</a></li>
    <li class="footer">生成于 2021年 二月 23日 星期二 16:39:17 , 为 develop-manual使用 
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.13 </li>
  </ul>
</div>
</body>
</html>
